config/routes.rb
Dolphins::Application.routes.draw do
  resources :subsets

  resources :swimsets

  resources :practices

  resources :variences

  resources :strokes

  resources :groups

end

app/models/practice.rb
class Practice < ActiveRecord::Base
 has_many :swimsets, dependent: :destroy, inverse_of: :practice
 accepts_nested_attributes_for :swimsets, allow_destroy: true
 belongs_to :group
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]

  # GET /practices
  # GET /practices.json
  def index
    @practices = Practice.all
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @practice }
      else
        format.html { render action: 'new' }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params.require(:practice).permit(:practicedate, :group_id, :lane, :compstatus, :comment)
    end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
<%= simple_form_for @practice, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :practicedate, label: "Date" %>
  <%= f.association :group %>
  <%= f.input :lane %>
  <%= f.input :compstatus, label: "Complete?" %>
  <%= f.input :comment %>
  <%= f.button :submit %>

<% end %>

app/views/practices/edit.html.erb
<%- model_class = Practice -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/practices/index.html.erb
<%- model_class = Practice -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:practicedate) %></th>
      <th><%= model_class.human_attribute_name(:group_id) %></th>
      <th><%= model_class.human_attribute_name(:lane) %></th>
      <th><%= model_class.human_attribute_name(:compstatus) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= link_to practice.id, practice_path(practice) %></td>
        <td><%= practice.practicedate %></td>
        <td><%= practice.group_id %></td>
        <td><%= practice.lane %></td>
        <td><%= practice.compstatus %></td>
        <td><%= practice.comment %></td>
        <td><%=l practice.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_practice_path(practice), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      practice_path(practice),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_practice_path,
            :class => 'btn btn-primary' %>

app/views/practices/new.html.erb
<%- model_class = Practice -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/practices/show.html.erb
<%- model_class = Practice -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:practicedate) %>:</strong></dt>
  <dd><%= @practice.practicedate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:group) %>:</strong></dt>
  <dd><%= @practice.group_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lane) %>:</strong></dt>
  <dd><%= @practice.lane %></dd>
  <dt><strong><%= model_class.human_attribute_name(:compstatus) %>:</strong></dt>
  <dd><%= @practice.compstatus %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @practice.comment %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              practices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_practice_path(@practice), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              practice_path(@practice),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>