config/routes.rb
Dolphins::Application.routes.draw do
  resources :subsets

  resources :swimsets

  resources :practices

  resources :variences

  resources :strokes

  resources :groups

end

app/models/subset.rb
class Subset < ActiveRecord::Base
	belongs_to :swimset, inverse_of: :subsets	
  	belongs_to :stroke, inverse_of: :subsets
  	belongs_to :varience, inverse_of: :subsets
end

app/controllers/subsets_controller.rb
class SubsetsController < ApplicationController
  before_action :set_subset, only: [:show, :edit, :update, :destroy]

  # GET /subsets
  # GET /subsets.json
  def index
    @subsets = Subset.all
  end

  # GET /subsets/1
  # GET /subsets/1.json
  def show
  end

  # GET /subsets/new
  def new
    @subset = Subset.new
  end

  # GET /subsets/1/edit
  def edit
  end

  # POST /subsets
  # POST /subsets.json
  def create
    @subset = Subset.new(subset_params)

    respond_to do |format|
      if @subset.save
        format.html { redirect_to @subset, notice: 'Subset was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subset }
      else
        format.html { render action: 'new' }
        format.json { render json: @subset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subsets/1
  # PATCH/PUT /subsets/1.json
  def update
    respond_to do |format|
      if @subset.update(subset_params)
        format.html { redirect_to @subset, notice: 'Subset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subsets/1
  # DELETE /subsets/1.json
  def destroy
    @subset.destroy
    respond_to do |format|
      format.html { redirect_to subsets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subset
      @subset = Subset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subset_params
      params.require(:subset).permit(:swimset_id, :distance, :stroke_id, :varience_id, :comment)
    end
end

app/helpers/subsets_helper.rb
module SubsetsHelper
end

app/views/subsets/_form.html.haml
=simple_form_for @subset, :html => { :class => 'form-inline' } do |f| 
  .form-inline.row-fluid
    //= f.input :swimset_id, :wrapper_html => {:class => "span1"} 
    .span1
      = f.input :distance, :class => "small-input"
    .span1
      = f.association :stroke, :class => "small-input"
    .span1
      = f.association :varience, label_method: :varience, value_method: :id, :class => "small-input"
  .row-fluid
    .span1
      = f.input :comment, :class => "large-input"
    .span1
      = f.button :submit, :class => "small-input"

app/views/subsets/_formBackup.haml
=simple_form_for (@subset, :html => { :class => 'form-horizontal' }) do |f| 
  .form-inputs.row
    = f.input :swimset_id, :wrapper_html => {:class => span2} 
    = f.input :distance, :wrapper_html => {:class => span2}
    = f.association :stroke, label_method: :stroke, value_method: :id, :wrapper_html => {:class => span2}
    = f.association :varience, label_method: :varience, value_method: :id, :wrapper_html => {:class => span2} 
    = f.input :comment, :wrapper_html => {:class => span2}
    = f.button :submit, :wrapper_html => {:class => span2}

<%= simple_form_for @subset, :html => { :class => 'form-horizontal' } do |f| %>

<DIV class="row">
  <DIV class="span1"> <%= f.input :swimset_id, :input_html => {:size => 20} %> </DIV>
  <DIV class="span1"> <%= f.input :distance, :input_html => {:size => 10} %> </DIV>
  <DIV class="span3"> <%= f.association :stroke, label_method: :stroke, value_method: :id, :input_html => {:size => 10}  %> </DIV>
  <DIV class="span3"> <%= f.association :varience, label_method: :varience, value_method: :id, :input_html => {:size => 10}   %> </DIV>
  <DIV class="span2"> <%= f.input :comment, :input_html => {:size => 10}  %> </DIV>
  <DIV class="span2"> <%= f.button :submit, :input_html => {:size => 10}  %> </DIV>
</DIV>

<% end %>

app/views/subsets/edit.html.erb
<%- model_class = Subset -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subsets/index.html.erb
<%- model_class = Subset -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:swimset_id) %></th>
      <th><%= model_class.human_attribute_name(:distance) %></th>
      <th><%= model_class.human_attribute_name(:stroke_id) %></th>
      <th><%= model_class.human_attribute_name(:varience_id) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subsets.each do |subset| %>
      <tr>
        <td><%= link_to subset.id, subset_path(subset) %></td>
        <td><%= subset.swimset_id %></td>
        <td><%= best_in_place subset, :distance %></td>
        <td><%= subset.stroke_id %></td>
        <td><%= subset.varience_id %></td>
        <td><%= best_in_place subset, :comment %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subset_path(subset), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subset_path(subset),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subset_path,
            :class => 'btn btn-primary' %>

app/views/subsets/new.html.erb
<%- model_class = Subset -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subsets/show.html.erb
<%- model_class = Subset -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:swimset_id) %>:</strong></dt>
  <dd><%= @subset.swimset_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:distance) %>:</strong></dt>
  <dd><%= @subset.distance %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stroke_id) %>:</strong></dt>
  <dd><%= @subset.stroke_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= best_in_place @subset, :comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:varience_id) %>:</strong></dt>
  <dd><%= @subset.varience_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              subsets_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subset_path(@subset), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subset_path(@subset),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>