config/routes.rb
Dolphins::Application.routes.draw do
  resources :subsets

  resources :swimsets

  resources :practices

  resources :variences

  resources :strokes

  resources :groups

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ILVY Dolphins</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">ILVY Dolphins</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Practices", practices_path %></li>
            <li><%= link_to "Swimsets", swimsets_path %></li>
            <li><%= link_to "Subsets", subsets_path %></li>
            <li><%= link_to "Groups", groups_path  %></li>
            <li><%= link_to "Strokes", strokes_path  %></li>
            <li><%= link_to "Variences", variences_path  %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class = "container">
	  <%= yield %>
  </div>
</body>
</html>